name: Linux

on:
  workflow_dispatch: # for manual workflow trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux_cpp17_gcc8:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install gcc8
        run: |
          sudo apt update
          sudo apt install -y gcc-8.3 g++-8.3
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
          cmake --build .

      - name: Test
        run: cd build && ./liteproto_test